[package]
name = "recovery_board"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded_utils = { path = "../embedded_utils" }

cortex-m = { workspace = true, features = ["critical-section-single-core"] }
cortex-m-rt = { workspace = true }

embassy-stm32 = { workspace = true, features = ["stm32g473rc", "time-driver-any", "memory-x"] }
embassy-time = { workspace = true, features = ["tick-hz-32_768"] }
embassy-executor = { workspace = true, features = ["arch-cortex-m", "executor-thread"] }
embassy-futures = { workspace = true }
embassy-sync = { workspace = true }

embedded-can = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-hal-bus = { workspace = true }

defmt = { workspace = true, optional = true }
defmt-rtt = { workspace = true, optional = true }

panic-probe = { workspace = true, optional = true }
panic-reset = { workspace = true }


hermes-can = { workspace = true, features = [
    "defmt",
    "message-separation-trigger",
    "message-deployment-trigger",
    "message-separation-occurred",
    "message-deployment-occurred",
    "message-steering-target-positions",
    "message-steering-actual-positions",
    "message-recovery-power-config",
    "message-recovery-board-status",
    "message-recovery-board-build-info",
] }

thiserror = { version = "2.0.11", default-features = false }

[build-dependencies]
built = { version = "0.7.7", features = ["git2"] }

[features]
default = ["debug"]
debug = ["defmt", "dep:panic-probe"]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "panic-probe/defmt",
    "panic-probe/defmt-error",
    "panic-probe/print-defmt",
    "embassy-executor/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-stm32/defmt",
    "embedded-hal-async/defmt-03",
    "embedded-hal-bus/defmt-03",
]

[[bin]]
name = "recovery_board"
test = false
doctest = false
bench = false
