# Adds defmt.x + a probe-rs runner; rest inherited from ../.cargo/config.toml.
[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tdefmt.x"]
runner = [
    "probe-rs",
    "run",
    "--chip",
    "STM32H723ZG",
    #"--no-catch-hardfault", # if the validation script faults, then we want to see it
    #"--no-catch-reset", # if the validation script resets, then we want to see it
    #"--chip-erase", # currently just faster to erase the written sections.
    "--log-format",
    "{t} {L:severity} {s}",
]

[env]
DEFMT_LOG = "debug"
