[package]
name = "asteria-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
wire-types = { path = "../../crates/wire-types", features = ["use-std"] }
postcard-rpc = { version = "0.12", features = ["use-std", "cobs-serial", "raw-nusb"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "signal"] }
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
async-trait = "0.1"
shell-words = "1.1"
rustyline = "14"
terminal_size = "0.4"
nusb = "0.1"
