[package]
name = "keller-pressure"
version = "0.1.0"
edition = "2024"
authors = ["Domenic Nebiker <dnebiker@aris-space.ch>"]
license = "MIT OR Apache-2.0"
description = "Driver for Keller Pressure Sensors over RS485"
keywords = ["embedded", "no-std", "embedded-hal", "sensor", "async"]

[dependencies]
embedded-utils = { path = "../../embedded-utils" }

embassy-stm32 = { workspace = true, features = ["stm32g473rc", "single-bank"] }
embassy-time = { workspace = true }

embedded-io-async = "0.7"
heapless = "0.9.1"
rmodbus = { version = "0.12.2", default-features = false, features = ["heapless"] }
bitflags = "2.9.4"

defmt = { version = "0.3", optional = true }

[features]
defmt = ["dep:defmt", "embassy-stm32/defmt", "rmodbus/defmt"]

[lib]
test = false
doctest = false
bench = false
