[package]
name = "fw-sensor-carrier"
version = "0.1.0"
edition = "2024"
authors = ["Louis Schell <louis.schell1@gmx.de>"]

[dependencies]
embedded-utils = { path = "../../crates/embedded-utils" }
ms5607 = { path = "../../crates/devices/ms5607", features = ["defmt-03"] }
lsm6dso32 = { path = "../../crates/devices/lsm6dso32", features = ["defmt-03"] }
can-utils = { path = "../../crates/can-utils" }
data-core = { path = "../../data-definitions/core", version = "0.1.0", features = ["can"] }
dp-sensor-carrier = { path = "../../data-definitions/datapoints/dp-sensor-carrier", version = "=0.3", features = [
    "can",
] }
dp-system-management = { path = "../../data-definitions/datapoints/dp-system-management", version = "=0.3", features = [
    "can",
] }
datatypes = { path = "../../data-definitions/datatypes" }
thiserror = { version = "2.0.11", default-features = false }
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embassy-stm32 = { version = "*", features = [
    "stm32h723zg",
    "time-driver-any",
    "memory-x",
    "unstable-pac",
    "exti",
] }
embassy-time = { version = "*", features = ["tick-hz-32_768"] }
embassy-executor = { version = "*", features = ["platform-cortex-m", "executor-thread"] }
embassy-futures = "*"
embassy-sync = "*"
embassy-embedded-hal = "*"
embedded-can = "0.4.1"
embedded-hal-async = "1.0.0"
embedded-hal-bus = { version = "0.3.0", features = ["async"] }
embedded-io-async = { version = "0.7", features = ["defmt"] }
defmt = { version = "1.0.1", optional = true }
defmt-rtt = { version = "1.0.0", optional = true }
panic-probe = { version = "1.0.0", optional = true }
panic-reset = "0.1.1"
atomic_enum = { version = "0.3.0", default-features = false }
# Drivers
lsm303agr = { version = "1.1.0", features = ["async"] }
sht4x = { version = "0.2.0", features = ["embedded-hal-async", "defmt"] }
ublox = { version = "0.4.5", default-features = false }
# Sensor fusion
imu-fusion = { git = "https://github.com/Rechenmaschine/imu-fusion-rs.git", default-features = false }
micromath = { git = "https://github.com/tarcieri/micromath", rev = "7139d27", features = [
    "defmt",
    "num-traits",
] }
minikalman = { version = "0.6.0", features = [] }
num-traits = { version = "0.2.19", default-features = false, features = [] }
nalgebra = { version = "0.33.2", default-features = false, features = [] }
simba = { version = "0.9.0", default-features = false, features = ["libm"] }
libm = "0.2.11"
# Utilities
heapless = "0.8.0"

[build-dependencies]
built = { version = "0.7.7", features = ["git2"] }

[features]
default = ["debug"]
debug = ["defmt", "dep:panic-probe"]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "can-utils/defmt",
    "data-core/defmt",
    "dp-sensor-carrier/derive_defmt",
    "dp-system-management/derive_defmt",
    "panic-probe/defmt",
    "panic-probe/defmt-error",
    "panic-probe/print-defmt",
    "embassy-executor/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-stm32/defmt",
    "embedded-hal-async/defmt-03",
    "embedded-hal-bus/defmt-03",
    "embedded-utils/defmt",
]

[[bin]]
name = "fw-sensor-carrier"
test = false
doctest = false
bench = false
