[package]
name = "embedded_utils"
version = "0.1.0"
edition = "2021"
authors = ["Louis Schell <louis.schell1@gmx.de>"]

[dependencies]
embassy-stm32 = { workspace = true, features = ["time-driver-any", "stm32g473rc"] }
embassy-time = { workspace = true, features = ["tick-hz-32_768"] }
defmt = { version = "0.3.10", optional = true }

[features]
defmt = ["dep:defmt"]

[lib]
name = "embedded_utils"
test = false
doctest = false
bench = false
