[package]
name = "oxidizer_control_board"
version = "0.1.0"
edition = "2021"
authors = ["Domenic Nebiker <dnebiker@aris-space.ch>"]

[dependencies]

keller_pressure = { path = "../devices/keller_pressure" }
max31889_thermistor = { path = "../devices/max31889_thermistor" }
ads1120_thermocouples = { path = "../devices/ads1120_thermocouples" }

embedded_utils = { path = "../../embedded_utils" }

cortex-m = { workspace = true, features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = { workspace = true }

embassy-stm32 = { workspace = true, features = [
    "stm32g473rc",
    "time-driver-any",
    "memory-x",
    "unstable-pac",
    "exti",
] }
embassy-time = { workspace = true, features = ["tick-hz-32_768"] }
embassy-executor = { workspace = true, features = ["arch-cortex-m", "executor-thread"] }
embassy-futures = { workspace = true }
embassy-sync = { workspace = true }

embedded-can = { workspace = true }
embedded-hal-async = { workspace = true }
embedded-hal-bus = { workspace = true, features = ["async"] }

defmt = { workspace = true, optional = true }
defmt-rtt = { workspace = true, optional = true }

panic-probe = { workspace = true, optional = true }
panic-reset = { workspace = true }

hermes-can = { workspace = true, features = [
    "defmt",
    "message-oxidizer-control-board-build-info",
    "message-oxidizer-control-board-status",
    "message-oxidizer-control-board-valve-states",
    "message-oxidizer-vent-control-ecu",
    "message-oxidizer-vent-control-fc",
    "message-oxidizer-vent-control-rfs",
    "message-oxidizer-dpr-config-ecu",
    "message-oxidizer-dpr-config-fc",
    "message-oxidizer-dpr-config-rfs",
    "message-oxidizer-tank-level",
    "message-oxidizer-tank-pressure",
    "message-fuel-tank-temperature",
    "message-oxidizer-pressurization",
    "message-oxidizer-pressurization-abort",
    "message-oxidizer-pressurization-gain",
] }

thiserror = { version = "2.0.11", default-features = false }

[build-dependencies]
built = { version = "0.7.7", features = ["git2"] }

[features]
default = ["debug"]
debug = ["defmt", "dep:panic-probe"]
defmt = [
    "dep:defmt",
    "dep:defmt-rtt",
    "panic-probe/defmt",
    "panic-probe/defmt-error",
    "panic-probe/print-defmt",
    "embassy-executor/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-stm32/defmt",
    "embedded-hal-async/defmt-03",
    "embedded-hal-bus/defmt-03",
    "max31889_thermistor/defmt-03",
    "ads1120_thermocouples/defmt",
    "keller_pressure/defmt",
]

[[bin]]
name = "oxidizer_control_board"
test = false
doctest = false
bench = false
