[package]
name = "trafag-pressure"
version = "0.1.0"
edition = "2024"
authors = ["Domenic Nebiker <dnebiker@aris-space.ch"]
description = "Driver for Trafag Pressure Sensors using Analog Inputs"
keywords = ["embedded", "no-std", "embedded-hal", "sensor", "async"]

[dependencies]
embassy-stm32 = { workspace = true, features = ["stm32g473rc", "unstable-pac", "single-bank"] }
cortex-m = { workspace = true }

defmt = { version = "0.3", optional = true }
embedded-utils = { path = "../../embedded-utils" }

[features]
defmt = ["dep:defmt"]

[lib]
test = false
doctest = false
bench = false
