[package]
name = "can-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = "*"
embassy-sync = "*"
embassy-executor = "*"
embedded-can = "0.4.1"
embedded-utils = { path = "../embedded-utils" }
can-hal = { path = "../../data-definitions/can-hal" }
collector-derive = { path = "./macros/collector" }
thiserror = { version = "2.0.18", default-features = false }
defmt = { version = "0.3", optional = true }

[features]
defmt = ["dep:defmt", "embassy-stm32/defmt"]
