[workspace]
resolver = "2"
members = ["app"]

[patch.crates-io]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy.git", rev = "cf6a6cd" }
postcard-rpc = { path = "../../asteria-firmware-test/vendor/postcard-rpc/source/postcard-rpc" }

[profile.dev]
debug = 2
debug-assertions = true
incremental = true
opt-level = 1
overflow-checks = true

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 3
overflow-checks = false
